apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: helloworld
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
        port: 80
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false