apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: spongebob-blog
spec:
  deployed: true
  powDifficultySeconds: 0
  horizontalPodAutoscalerSpec:
    maxReplicas: 24
    minReplicas: 24
    targetCPUUtilizationPercentage: 60
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
        port: 80
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false